apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1 
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4
        ports:
        - name: mongodb-port
          containerPort: 27010
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        env:
        - name: MONGO_INITDB_DATABASE
          value: mongodb
        - name: MONGO_INITDB_ROOT_USERNAME
          value: mongodb
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: mongodb
      volumes:
      - name: mongodb-data
        emptyDir: {}