apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb # Optional metadata label
spec:
  selector:
    app: mongodb # MUST match the labels in the Deployment/Pod spec
  ports:
    - protocol: TCP
      port: 27017 # Port exposed by the service
      targetPort: 27017 # Port the MongoDB container listens on
  type: ClusterIP      # Options: ClusterIP, NodePort, LoadBalancer
