apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: k8-boss-consumer:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: boss-config
